services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/user-management/backend/src
      - ./pom.xml:/user-management/backend/pom.xml
    restart: always

  db:
  

networks:
  driver: default